config/routes.rb
# Updating routes? Please update the readme as well.

Rails.application.routes.draw do
  resources :items, except: [:destroy] do
    resources :item_comments
    member do
      post :toggle
      post :vote, to: 'user_item_votes#create'
      delete :vote, to: 'user_item_votes#destroy'
    end
  end

  root to: 'items#index'

  resources :users, except: [:index]
  resources :user_sessions, only: [:new, :create, :destroy]

  get 'login' => 'user_sessions#new', as: :login
  match 'logout' => 'user_sessions#destroy', as: :logout, via: [:get, :post]

  namespace :admin do
    root to: 'items#index'
    resources :items
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!

  before_create do
    begin
      self.token = SecureRandom.hex
    end while self.class.exists?(token: token)
  end

  validates :password, length: { minimum: 5 }, if: :password
  validates :password, confirmation: true, if: :password
  validates :password_confirmation, presence: true, if: :password

  validates :username, uniqueness: true, length: {minimum: 2}

  has_many :items
  has_many :votes
  has_many :item_comments

  def item_votes
    votes.where(votable_type: "Item")
  end

  def to_param
    username.downcase
  end

  def username
    disabled? ? "[deleted]" : read_attribute(:username)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_login, only: [:edit, :update, :destroy]
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def new
    # user registration page
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      auto_login(@user)
      redirect_to root_path, notice: 'User was successfully created.'
    else
      render :new
    end
  end

  def show
    #   profile page
  end

  def edit
    #   profile edit
  end

  def update
    if @user.update(user_params)
      redirect_to @user, notice: 'User was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @user.destroy
    redirect_to root_path, notice: 'User was successfully destroyed.'
  end

  private
  def set_user
    @user = User.where(username: params[:id]).first
    unless @user
      return redirect_back_or_to root_path, notice: 'could not find user'
    end
  end

  # Only allow a trusted parameter "white list" through.
  def user_params
    params.require(:user).permit(
      :username,
      :password,
      :password_confirmation,
      :about
    )
  end
end

app/views/users/_form.html.erb
<%= simple_form_for(@user, html: { class: 'form-horizontal' }) do |f| %>
  <%= f.error_notification %>
  <%= f.input :username %>
  <%= f.input :password, as: :password %>
  <%= f.input :password_confirmation, as: :password %>
  <%= f.input :about %>
  <div class="row">
    <%= f.button :submit, class: 'btn-block' %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing Users</h1>
<ul class="list-unstyled">
  <% @users.each do |user| %>
    <li><%= link_to user.username, user %></li>
  <% end %>
</ul>

app/views/users/new.html.erb
<div class="col-lg-5">
  <h1>New User</h1>
  <%= render 'form' %>
</div>

app/views/users/show.html.erb
<p>
  <strong>Username:</strong>
  <%= @user.username %>
</p>


<p>
  <strong>Karma:</strong>
  <%= @user.karma %>
</p>


<p>
  <strong>About:</strong>
  <%= @user.about %>
</p>