config/routes.rb
# Updating routes? Please update the readme as well.

Rails.application.routes.draw do
  resources :items, except: [:destroy] do
    resources :item_comments
    member do
      post :toggle
      post :vote, to: 'user_item_votes#create'
      delete :vote, to: 'user_item_votes#destroy'
    end
  end

  root to: 'items#index'

  resources :users, except: [:index]
  resources :user_sessions, only: [:new, :create, :destroy]

  get 'login' => 'user_sessions#new', as: :login
  match 'logout' => 'user_sessions#destroy', as: :logout, via: [:get, :post]

  namespace :admin do
    root to: 'items#index'
    resources :items
  end
end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :user
  has_many :votes, as: :votable
  has_many :comments, class_name: "ItemComment"

  validates :title, presence: true, length: { maximum: 250 }, allow_blank: false, allow_nil: false
  validates :id, uniqueness: true

  validate do
    if content.blank? && url.blank?
      errors.add(:url, 'Submit a URL or Content')
    end
    if content.present? && url.present?
      errors.add(:url, 'Submit a URL or Content but not Both.')
    end
  end
  validates :url, url: {allow_nil: true, allow_blank: true}


  scope :active, -> { where(disabled: false) }
  scope :disabled, -> { where(disabled: true) }
  scope :newest, -> { order(score: :desc) }
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action do
    current_admin = !!(current_user && current_user.admin?)
    unless current_admin
      redirect_to root_path, alert: "Unauthorized."
    end
  end
  before_action :set_admin_item, only: [:show, :edit, :update, :destroy]

  def index
    @admin_items = Item.all
  end

  def show
  end

  def new
    @admin_item = Item.new
  end

  def edit
  end

  def create
    @admin_item = current_user.items.build(admin_item_params)

    respond_to do |f|
      if @admin_item.save
        f.html {redirect_to @admin_item, notice: 'Item was successfully created.'}
        f.json {render json: @admin_item}
      else
        f.html {render action: 'new'}
        f.json {render json: @admin_item.errors, status: :unprocessable_entity}
      end
    end
  end

  def update
    if @admin_item.update(admin_item_params)
      redirect_to @admin_item, notice: 'Item was successfully updated.'
    else
      render action: 'edit'
    end
  end

  def destroy
    @admin_item.destroy
    redirect_to admin_items_url
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_admin_item
    @admin_item = Item.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def admin_item_params
    params.require(:item).permit(*Item.new.attributes.keys)
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :require_login, only: [:new, :create, :edit, :update, :toggle]
  before_action :set_item, only: [:show]
  before_action :set_user_item, only: [:edit, :update, :toggle]

  def index
    order = params[:newest] ? {created_at: :desc} : {rank: :desc}

    @items = Item.order(order).includes(:user)
    @votes = @items.includes(:votes).each_with_object({}) do |item, object|
      object[item.id] = item.votes.map(&:user_id)
    end
  end

  def show
    @comments = @item.comments.includes(:user).order(created_at: :asc)
  end

  def new
    @item = Item.new
  end

  def edit
  end

  def create
    @item = current_user.items.build(item_params)

    if @item.save
      redirect_to @item, notice: 'Item was successfully created.'
    else
      render :new
    end
  end

  def update
    if @item.update(item_params)
      redirect_to @item, notice: 'Item was successfully updated.'
    else
      render :edit
    end
  end

  def toggle
    @item.update(:disabled, @item.disabled?)
    message = item.disabled? ? 'disabled' : 'enabled'
    redirect_to @item, notice: "Item #{message}."
  end

  private
  def set_item
    @item = Item.includes(:votes).find(params[:id])
    @votes = [@item].each_with_object({}) do |item, object|
      object[item.id] = item.votes.map(&:user_id)
    end
  end

  def set_user_item
    @item = current_user.items.where(id: params[:id]).first
    unless @item
      redirect_to :back, notice: 'Unauthorized'
      return
    end
  end

  def item_params
    params.require(:item).permit(:title, :url, :content)
  end
end

app/views/items/_form.html.erb
<%= simple_form_for(@item) do |f| %>
  <%= f.error_notification %>

  <%= f.input :title %>
  <%= f.input :url, as: :url, label: false, placeholder: "URL" %>
  <div>or</div>
  <%= f.input :content, as: :text, label: false, placeholder: "Markdown Description" %>
  <div>
    Leave url blank to submit a question for discussion. If there is no url, the text (if any) will appear at the top
    of the thread.
  </div>

  <%= f.button :submit %>
<% end %>

app/views/items/_item.html.erb
<li class="media">
  <div class="media-left">
    <a href="#">
      <%= render_votes_for_item(item) %>
    </a>
  </div>
  <div class="media-body">
    <h4 class="media-heading">
      <% if item.url.present? %>
        <%= link_to item.title, item.url, title: item.url, target: '_blank' %>
        <small>(<%= URI.parse(item.url).host %>)</small>
      <% else %>
        <%= link_to item.title, item, title: truncate(item.content, length: 30) %>
        <small><%= link_to '[discussion]', item %></small>
      <% end %>
    </h4>
    <small>
      <%= item.score %> points
      by <%= render_link_to_user(item.user) %> <%= link_to "#{time_ago_in_words(item.created_at)} ago", item %>
      | <%= link_to "#{item.comments_count} comments", item %>
    </small>
  </div>
</li>

app/views/items/edit.html.erb
<h1>Editing Item</h1>

<%= render 'form' %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<% content_for :headerwrap do %>
  <%= render 'components/login_register' %>
<% end %>

<ul class="media-list">
  <%= render @items %>
</ul>

app/views/items/new.html.erb
<h1>Submit URL or markdown content</h1>

<%= render 'form' %>

app/views/items/show.html.erb
<p>
  <strong>[score: <%= @item.score %>]</strong>
  <%= render_votes_for_item(@item) %>
  <span>comments: <%= @item.comments_count %></span>
</p>
<%= content_for(:title) do %>
  <%= @item.title %>
<% end %>
<p>
  <strong>
    <h1><%= link_to @item.title, @item, title: @item.url %></h1>
    <small>(<%= @item.url %>)</small>
  </strong>
  <span><small>(posted by: <%= link_to @item.user.username, @item.user %>)</small></span>
</p>

<ul>
  <% if current_user %>
    <li>
      <%= simple_form_for([@item, current_user.item_comments.build]) do |f| %>
        <%= f.input :content, label: false, required: true %>
        <%= f.button :submit %>
      <% end %>
    </li>
  <% end %>

  <% @comments.each do |comment| %>
    <%= content_tag_for(:li, comment) do %>
      <span>
        created: <%= link_to time_ago_in_words(comment.created_at), item_path(@item, anchor: "comment") %> ago.
        <small>(posted by: <%= link_to comment.user.username, comment.user %>)</small>
      </span>
      <br/>
      <small>
        <%= comment.content %>
      </small>
    <% end %>
  <% end %>
</ul>