config/routes.rb
# Updating routes? Please update the readme as well.

Rails.application.routes.draw do
  resources :items, except: [:destroy] do
    resources :item_comments
    member do
      post :toggle
      post :vote, to: 'user_item_votes#create'
      delete :vote, to: 'user_item_votes#destroy'
    end
  end

  root to: 'items#index'

  resources :users, except: [:index]
  resources :user_sessions, only: [:new, :create, :destroy]

  get 'login' => 'user_sessions#new', as: :login
  match 'logout' => 'user_sessions#destroy', as: :logout, via: [:get, :post]

  namespace :admin do
    root to: 'items#index'
    resources :items
  end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  before_action :require_login, only: [:destroy]

  def new
    @user = User.new
  end

  def create
    if @user = login(login_params[:username], login_params[:password])
      redirect_back_or_to root_path, notice: 'Login successful'
    else
      render action: 'new', notice: 'Try Again'
    end
  end

  def destroy
    logout
    redirect_to root_path, notice: 'Logged out!'
  end

  private
  def login_params
    params.require(:login).permit(:username, :password)
  end
end

app/views/user_sessions/_form.html.erb
<%= simple_form_for :login, html: {class: 'form-horizontal'}, url: user_sessions_path, method: :post do |f| %>
  <%= f.input :username %>
  <%= f.input :password %>
  <div class="row">
    <%= f.button :submit, "Login", class: 'btn-block' %>
  </div>
<% end %>

app/views/user_sessions/create.html.erb
<h1>UserSessions#create</h1>
<p>Find me in app/views/user_sessions/create.html.erb</p>

app/views/user_sessions/destroy.html.erb
<h1>UserSessions#destroy</h1>
<p>Find me in app/views/user_sessions/destroy.html.erb</p>

app/views/user_sessions/new.html.erb
<div class="col-lg-12">
  <h1>Login</h1>
</div>
<div class="col-lg-5">
  <%= render 'form' %>
</div>
<div class="col-lg-7">
  Here you can say some stuff about signing in!
</div>